<?php
// $Id: ckeditor_config.module,v 1.00 2010/10/23 00:25:00 brightbold Exp $

/**
 * @file
 *
 * This module allows you to prevent CKEditor from turning quotation marks into
 * &quot; entities, which breaks Typogrify.
 * Code per TwoD, http://drupal.org/node/803562#comment-3219142
 *
 */

/**
 * Implementation of hook_wysiwyg_editor_settings_alter().
 */
function ckeditor_config_wysiwyg_editor_settings_alter(&$settings, &$context) {
  if($context['profile']->editor == 'ckeditor') {
    $settings['entities'] = FALSE;
    $settings['forceSimpleAmpersand'] = TRUE;
  }
}
